<?php
$allowedip = array("111.243", "1.171", "61.230", "220.135", "61.220", "60.251");//"::1."
$arrMedDay = array("一Mon","二Tues","三Wed","四Thur","五Fri","六Sat","日Sun","每天Everyday","隔天Every 2 days"); //Monday~Sunday and 1day in 1 day off
$arrYesNo = array('---','是Yes','否No'); //---,yes,no
$arrGender = array('Unfilled','Male','Female');//unfilled, male,female
$arrInPatStatus = array('---','已登記Registered','入住中Checked-in');//---,signed in, already Habitated
$arrDay = array('7','1','2','3','4','5','6'); //菜單用 for meal manu
$arrVital = array('8310-5'=>'Temp.', '8867-4'=>'心跳Heart Beat', '8480-6'=>'收縮壓Systolic blood pressure', '8462-4'=>'舒張壓Diastolic blood pressure', '2710-2'=>'SpO2', '14743-9'=>'Blood glucose before meals', '15075-5'=>'飯後血糖Blood glucose after meals', '3141-9'=>'weight', '9279-1'=>'呼吸次數Respiratory rate', '18833-4'=>'weight');
    //8310-5 body temperature, 8867-4 heardbeat record, 8480-6 Systolic blood pressure, 8462-4 Diastolic blood pressure, 2710-2 Blood oxygen Oximetry,14743-9 Blood sugar before meals,15075-5Blood sugar after meals,3141-9 weight,9279-1 breath count per minute,18833-4 weight
$arrVitalConvert = array('Ear'=>'8310-5', 'Pulse'=>'8867-4', 'Sys'=>'8480-6', 'Dia'=>'8462-4', 'SpO2'=>'2710-2', 'BG'=>'14743-9', 'BG'=>'15075-5');
$arrNursediag = array('1' => '呼吸道清除Airway clearance', '2' => '低效性呼吸型態Ineffective breathing pattern', '3' => '身體活動功能障礙Physical activity dysfunction', '4' => '排便管型態改變便秘Change status of bowel tube-constipation', '5' => '排便型態改變腹瀉Change status of bowel tube-diarrhea', '6' => '吞噬消化功能障礙Phagocytic digestive dysfunction', '7' => '營養狀況改變少於身體所需Nutrition status change-less than body needs', '8' => '營養狀況改變多於身體所需Nutrition status change-more than body needs', '9' => '現存性皮膚完整性受損傷口Existing skin integrity impaired-wound', '10' => '舒適情形改變-體溫過高Comfort status change - hyperthermia', '11' => '舒適情形改變-搔癢Comfort status change - itching', '12' => '體液容積過多Excessive fluid volume', '13' => '高危險性呼吸道感染Hazardous respiratory infection', '14' => '高危險性尿道感染Hazardous urinary tract infections', '15' => '高危險性傷害-跌倒Hazardous event-falls', '16' => '感覺及知覺改變-視、聽、方位感Sensory and perceptual change - vision, hearing, sense of direction', '17' => '自我照顧能力缺失-沐浴與清潔衛生Lack of self-care skills - bathing and hygiene', '18' => '自我照顧能力缺失-穿著修飾Lack of self-care skills - wearing and accessory ', '19' => '自我照顧能力缺失-進食Lack of self-care skills -dieting', '20' => '自我照顧能力缺失-如廁Lack of self-care skills -toileting', '21' => '睡眠型態OrderlessSleep patterns confusion', '22' => '焦慮新住民適應問題Anxiety new adaptation Resident', '23' => '保護性約束Protection constraints', '24' => '口腔黏膜改變Oral mucosal changes', '25' => '潛在危險性感染：導尿管留置Potentially dangerous infections: indwelling catheter', '26' => '潛在危險性傷害：跌倒Potentially dangerous wound:falls', '27' => '舒適情形改變—疼痛Comfort status change - pain', '28' => '管路移除-尿管留置Piping removed - indwelling catheter');
// 1 Airway clearance, 2 Ineffective breathing pattern, 3 Physical activity dysfunction, 4 bowel pattern change :Constipation, 5 bowel pattern change :Diarrhea,6 Phagocytic digestive dysfunction, 7 Nutritional status change: lower then body need,8 Nutritional status change: higher then body need, 9 existed skin Integrity impaired wound, 10 comfort status change: high Temp., 11 comfort status change:Itching,12 Excessive fluid volume, 13serious hazard:Respiratory infections,14serious hazard:Urinary tract infections,15serious hazard: fall
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                      16 Sensory and perceptual changes: visual/auditory/direction,17 Self care deficit-bathing and hygiene,18 Self care deficit-clothing and accessory,19 Self care deficit-intake(eating),20Self care deficit-Toileting ,21 Sleep patterns disorder, 22 Anxiety and new residents adaptation problem,23 Protective restraint, 24 Oral mucosal changes,25 Potentially dangerous infections:indwelling urine catheter,26 Potentially dangerous wound: fall, 27 comfort status change-Pain, 28 Piping removed - the indwelling catheter
$arrFormFreq = array(
//value X 為X天填寫一次，只需填寫一次的表單 X=99    X means, written 1 time/ X day
'nurseform01' => 99, 'nurseform01a' => 99, 'nurseform02a' => 99, 'nurseform02b' => 90, 'nurseform02c' => 90, 'nurseform02d' => 90, 'nurseform02e' => 90, 'nurseform02f' => 90,  'nurseform02g' => -1, 'nurseform02g_1' => -1, 'nurseform02g_2' => -1, 'nurseform02h' => 90, 'nurseform02j' => -1, 'nurseform11' => 3, 'nurseform12' => 3, 'nurseform16' => 0, 'nursediag01' => -1, 'nursediag02' => -1, 'nursediag03' => -1, 'nursediag04' => -1, 'nursediag05' => -1, 'nursediag06' => -1, 'nursediag07' => -1, 'nursediag08' => -1, 'nursediag09' => -1, 'nursediag10' => -1, 'nursediag11' => -1, 'nursediag12' => -1, 'nursediag13' => -1, 'nursediag14' => -1, 'nursediag15' => -1, 'nursediag16' => -1, 'nursediag17' => -1, 'nursediag18' => -1, 'nursediag19' => -1,'nursediag20' => -1, 'nursediag21' => -1, 'nursediag22' => -1, 'nursediag23' => -1, 'nursediag24' => -1, 'nursediag25' => -1, 'nursediag26' => -1, 'nursediag27' => -1, 'nursediag28' => -1
);
$arrFormHospital = array('Hospital 1','Hospital 2','Hospital 3','Hospital 4','Hospital 5','Hospital 6','Hospital 7','Hospital 8','Hospital 9','Other'); //The main hospitals, else in the end
$arrForm16_Q4 = array("1" =>'急診ER', "2" =>'門診Intatient');//1=>ER(Emergency),2=> Outpatient clinic?
$arrForm2k_Q1 = array("1"=>"Catheter(Foley)","2"=>"Catheter-Cystostomy(Foley)","3"=>"Nasogastric tube(NG tube)", "4"=>"Tracheal tube");//1->urine Catheter,2->urine Catheter-Cystostomy
$arrForm2k_Q2 = array("1"=>"一般General", "2" =>"矽膠Silicone");//1->ordinary,2->Silicone
$arrSocialform05_Q1 = array("1"=>"適應問題Adaptation problem", "2"=>"情緒問題Emotional problem", "3"=>"行為問題Behavioural problem", "4"=>"健康問題Health problem", "5"=>"經濟問題Economic issues", "6"=>"家庭問題Family problem", "7"=>"Other");//1 adaptation problem,2 Emotional problem,3 behavioural problem,4 health problem,5 Economic issues(problem),6 family problem,7 other
$arrSocialform06a_Q33 = array("0"=>"未評估Not yet evaluate", "1"=>"無適應問題，一般個案服務模式No adaptation problem-general casework service mode", "2"=>"有適應問題，特殊服務模式Adaptation challenged-Special service mode");// 0 not yet evaluate, 1 No adaptation problem-general casework service mode,2 Adaptation challenged-Special service mode 
?>